name: CI Activity Tests
defaults:
  run:
    shell: bash
on:
 push:
  branches: 
   - main
 pull_request:
  branches: 
   - main
jobs:

 build_job:
  runs-on: ubuntu-20.04
  steps:
  - name: Update
    run: sudo apt update
  - name: apt install
    run: sudo apt install -y nodejs
  - name: npm install
    run: npm install
  - name: test
    run: npm run test
