name: CI Activity Tests
on:
 push:
branches: [ main ]
 pull_request:
branches: [ main ]
jobs:
 do_the_build_please:
runs-on: ubuntu-20.04
steps:
- uses: actions/checkout@v3
- name: Update repos
 run: sudo apt update
- name: Install node
 run: sudo apt install -y nodejs
- name: Install deps
 working-directory: ${{github.workspace}}
 run: npm install --include=dev
- name: Test
 working-directory: ${{github.workspace}}
 run: npm run test
