name: CI Activity Tests
defaults:
  run:
    shell: bash
on:
 push:
  branches: 
   - main
 pull_request:
  branches: 
   - main
jobs:

 build_job:
  runs-on: ubuntu-latest
  steps:
  - run: |
      npm install
  - name: test
    run: npm run test
